- id: doi:10.1101/2024.10.04.616668
  publisher: BioRxiv
  image: ../pdf/BALLbiorxiv.png
  buttons:
    - type: pdf
      link: ../pdf/BALLbiorxiv.pdf
      
- id: doi:10.1101/2024.09.14.613043
  publisher: BioRxiv
  image: ../pdf/STAG2biorxiv.png
  buttons:
    - type: pdf
      link: ../pdf/STAG2biorxiv.pdf

- id: doi:10.1038/s41586-022-05504-4
  image: ../pdf/nature2022.png
  buttons:
    - type: pdf
      link: ../pdf/nature2022.pdf
 
- id: doi:10.1101/gad.335794.119
  image: ../pdf/GD2020.png
  buttons:
    - type: pdf
      link: ../pdf/GD2020.pdf
 
- id: doi:10.1093/bfgp/elz026
  image: ../pdf/review2019.png
  buttons:
    - type: pdf
      link: ../pdf/review2019.pdf

- id: doi:10.1093/nar/gkx1277
  image: ../pdf/NAR2018.png
  buttons:
    - type: pdf
      link: ../pdf/NAR2018.pdf

- id: doi:10.14800/rd.1492

- id: doi:10.1093/nar/gkw1261
  image: ../pdf/NAR2016.png
  buttons:
    - type: pdf
      link: ../pdf/NAR2016.pdf
