- id: doi:10.1038/s41586-022-05504-4
  publisher: Nature
  image: pdf/nature2022.png
  buttons:
      - type: pdf
        link: pdf/nature2022.pdf
- id: doi:10.1101/gad.335794.119
  publisher: Genes &amp; Development
 
- id: doi:10.1093/bfgp/elz026
  publisher: Briefings in Functional Genomics

- id: doi:10.1093/nar/gkx1277
  publisher: Nucleic Acids Research

- id: doi:10.14800/rd.1492
  publisher: RNA &amp; DISEASE

- id: doi:10.1093/nar/gkw1261
  publisher: Nucleic Acids Research
