- id: doi:10.1101/2024.10.04.616668
  image: ../images/publications/BALLbiorxiv.png
  publisher: BioRxiv

- id: doi:10.1101/2024.09.14.613043
  image: ../images/publications/STAG2biorxiv.png
  publisher: BioRxiv

- id: doi:10.1038/s41586-022-05504-4
  image: https://media.springernature.com/m312/springer-static/image/art%3A10.1038%2Fs41586-022-05504-4/MediaObjects/41586_2022_5504_Fig1_HTML.png
 
- id: doi:10.1101/gad.335794.119
  image: images/publications/GD2020.png
 
- id: doi:10.1093/bfgp/elz026
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bfg/19/2/10.1093_bfgp_elz026/5/m_elz026f2.jpeg?Expires=1730760873&Signature=PRPK4MNusYsQWVzeIWHS~f~R6lXLg4HOOwcakrwnzFnYOG20jVtSj2uFH-WyJVCvx7gR4WxR4OjR3dCy57Q7nbZMIus-mhuphKy9CTbJChAJbhebLP8bu8IvGtqfgaWmfmBk61tkOe8KFQfFgbjfML3kqyQwf~E3L1efdexKe9JQFbeIo6OevcghPys9TitchhD6pMo2XOkoSApDeaoYB8s5hWiUA6y2StASuCXMUvs5~jwGM8tjSkKewkmuItt25I37LQEGB2dP31zG5IzFnmJmShWD~fvn2oLpBjCeeuVoHdtb99L1GDl08xUC1b8nidEQp~DEwiWetlp4oRcJXw__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1093/nar/gkx1277
  image: images/publications/NAR2018.png

- id: doi:10.14800/rd.1492

- id: doi:10.1093/nar/gkw1261
  image: images/publications/NAR2016.png
