- id: doi:10.1101/2024.10.04.616668
  image: ../images/publications/BALLbiorxiv.png
  publisher: BioRxiv

- id: doi:10.1101/2024.09.14.613043
  image: ../images/publications/STAG2biorxiv.png
  publisher: BioRxiv

- id: doi:10.1038/s41586-022-05504-4
  image: ../images/publications/nature2022.png
 
- id: doi:10.1101/gad.335794.119
  image: ../images/publications/GD2020.png
 
- id: doi:10.1093/bfgp/elz026
  image: ../images/publications/review2019.png

- id: doi:10.1093/nar/gkx1277
  image: ../images/publications/NAR2018.png

- id: doi:10.14800/rd.1492

- id: doi:10.1093/nar/gkw1261
  image: ../images/publications/NAR2016.png
